import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GitScope",
  description: "GitScope-AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex-grow">
          {children}
        </div>
        <footer className="py-4 text-center text-xs text-neutral-500 font-mono w-full border-t border-white/5 bg-[#050505]">
          ⚠️ Note: These insights are generated by AI and are for informational and entertainment purposes. They may not be 100% accurate.
        </footer>
      </body>
    </html>
  );
}
